/**
 * Represents a basic fixture/event without odds. 
 * Fetched from GET /v4/sports/{sport}/events
 * Note: This endpoint costs 0 usage quota credits.
 */
export interface Event {
  /** The unique match identifier generated by The Odds API */
  id: string;
  /** The specific sport/league routing key */
  sport_key: string;
  /** The specific sport/league human readable title */
  sport_title: string;
  /** ISO 8601 Timestamp of when the match officially starts */
  commence_time: string;
  /** Team playing at home */
  home_team: string;
  /** Team travelling */
  away_team: string;
}
