/**
 * Represents a single pricing outcome within a market
 */
export interface Outcome {
  /** Usually the team name, or "Draw" / "Over" / "Under" */
  name: string;
  /** The decimal payout multiplier or american odds based on request format */
  price: number;
  /** Optional spread or total line (e.g., 6.5 for a spread bet) */
  point?: number;
}

/**
 * Represents a specific betting market (e.g., Head to Head, Spreads)
 */
export interface Market {
  /** e.g., "h2h", "spreads", "totals" */
  key: string;
  /** The available bets within this market */
  outcomes: Outcome[];
}

/**
 * Represents pricing data from a specific bookmaker for a single game
 */
export interface Bookmaker {
  /** The unique identifier for the bookie (e.g., "unibet") */
  key: string;
  /** Display name (e.g., "Unibet") */
  title: string;
  /** ISO 8601 Timestamp of when these odds were last refreshed */
  last_update: string;
  /** The betting markets offered by this bookmaker */
  markets: Market[];
}

/**
 * Represents the full response object for a single game from:
 * GET https://api.the-odds-api.com/v4/sports/{sport_key}/odds/
 */
export interface GameOdds {
  /** The unique match identifier generated by The Odds API */
  id: string;
  /** The specific sport/league routing key */
  sport_key: string;
  /** The specific sport/league human readable title (e.g. "NFL") */
  sport_title?: string;
  /** ISO 8601 Timestamp of when the match officially starts */
  commence_time: string;
  /** Team playing at home */
  home_team: string;
  /** Team travelling */
  away_team: string;
  /** Array of available odds from various providers */
  bookmakers: Bookmaker[];
}
